Feature/get order
wecode-bootcamp-korea/49-3rd-ifAreYouT-backend pull request #12
Opened 2023-10-17 14:48 UTC by namsuhan0322

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
- 마이페이지에서 예매내역 조회를 할수있게 만들었습니다

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
- 주문한 내역을 빠르게 확인할수있다 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

(예시) 로그인 기능 추가
마이페이지- 예매내역 조회 기능 추가

-예매 내역이 없을시 PURCHASE_HISTORY_NOT_FOUND

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

- (drag & drop 또는 첨부파일 추
<img width="465" alt="스크린샷 2023-10-17 오후 7 39 00" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/142658057/44783372-3fd0-4f9a-9fe4-9770405b4dd7">
가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

2023-10-18 04:11 UTC, soheon-lee commented
1. 첫번째 올리신 PR이랑 대부분의 수정 사항이 겹칠 것 같습니다.
2. 해당 API는 주문을 관리하는 API이기 때문에 orderRouter, orderController, orderService, orderDao로 전부 이동/수정 해주세요! :)

2023-10-18 15:12 UTC, soheon-lee reviewed
1. 아래 코멘트들 확인해주세요~
2. 마찬가지로 TEST 통과하지 못하고 있습니다. 확인 부탁드립니다!

<img width="859" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/42701133/143a1ab2-554f-4146-8a26-c00eeec3ef39">

2023-10-18 15:12 UTC, soheon-lee commented on src/controllers/orderlistController.js
> +    const checkUserOrder = await orderlistService.getCheckOrderList(userId);
```suggestion
    const checkUserOrder = await orderService.getCheckOrderList(userId);
```

order데이터를 관리하는 service에서 주문 '목록'만을 관리하지 않을 것이기 때문에 전제 파일(router, controller, service, model)에서 list라는 단어는 제거해 주세요 :)

2023-10-18 15:12 UTC, soheon-lee commented on src/models/orderlistDao.js
> +    `
getUserCheckOrder에서 check가 무슨 뜻을 갖고 있나요???

2023-10-18 15:12 UTC, soheon-lee commented on src/models/orderlistDao.js
> +  );
들여쓰기 해주세요

2023-10-18 15:12 UTC, soheon-lee commented on src/routes/orderlistRouter.js
> +
```suggestion
const express = require('express');
const { orderlistController } = require('../controllers');
const router = express.Router();

```

controllers가 패키지 이기 때문에, 패키지의 특징을 활용해서, 직접 모듈에 접근하지 않아도 됩니다.

2023-10-18 15:12 UTC, soheon-lee commented on src/services/orderlistService.js
> +};
```suggestion

const getOrderByUserId = async (userId) => {
  return await orderlistDao.getUserCheckOrder(userId);
};

module.exports = {
  getCheckOrderList
};
```

2023-10-19 07:35 UTC, soheon-lee commented
@namsuhan0322 컨플릭트 해결해 주세요 :)

2023-10-19 07:56 UTC, namsuhan0322 commented
컨플릭트 수정 했습니다!

2023-10-19 14:07 UTC, soheon-lee approved these changes
함수 이름 명명하실 때, 아직 조금 더 훈련이 필요하실 것 같아요 :) 어떤 entity를 어떻게 만드는지 보다 명확히 이름 지어주세요! 함수 이름만 변경하시고 나면 self 머지 하셔도 됩니다! 수고하셨어요-!

2023-10-19 14:07 UTC, soheon-lee commented on db/schema.sql
> +=======
수한님 여기 컨플릭트 해결하시다 남은 사항들이 좀 있어요! 크리티컬한 거라 고치셔야 합니다 -!

2023-10-19 14:07 UTC, soheon-lee commented on src/models/index.js
> +module.exports = { ticketDao,orderDao }
```suggestion
module.exports = { ticketDao, orderDao }
```

2023-10-19 14:07 UTC, soheon-lee commented on src/models/orderDao.js
> +const getUserByOrder = async (userId) => {
```suggestion
const getOrderByUsersId = async (userId) => {
```

2023-10-19 14:15 UTC, soheon-lee requested changes
컨플릭트 난 파일 꼭 수정해 주세요 :)

2023-10-20 03:31 UTC, soheon-lee requested changes
테스트 케이스 body랑 함수명만 조금 더 고치면 머지 할 수 있을 것 같습니다 :)

2023-10-20 03:31 UTC, soheon-lee commented on src/routes/orderRouter.js
> +
```suggestion

router.get("/", verificateToken, orderController.getUserOrder)


```

2023-10-20 03:31 UTC, soheon-lee commented on src/services/orderService.js
> +  const orderInfo = orderDao.getOrderByUsersId(userId);
```suggestion
  const orderInfo = orderDao.getOrderByUserId(userId);
```

2023-10-20 03:31 UTC, soheon-lee commented on src/controllers/orderController.js
> +const getUserOrderController = async (req, res) => {
```suggestion
const getUserOrder = async (req, res) => {
```

2023-10-20 03:31 UTC, soheon-lee commented on src/models/orderDao.js
> +const getOrderByUsersId = async (userId) => {
```suggestion
const getOrderByUserId = async (userId) => {
```

2023-10-20 03:31 UTC, soheon-lee commented on src/routes/orderRouter.js
> +const { verificateToken } = require('../middlewares')
```suggestion
const { verifyToken } = require('../middlewares')
```
- verificate라는 단어가 없지 않나요?
- 팀내 공유하셔서 단어 적절한걸로 수정 부탁드립니다 :)

2023-10-20 03:31 UTC, soheon-lee commented on tests/userOrder.test.js
> +    }
expect(res.body)로 data키 값에 들어가있는 orderInfo도 모두 테스트 하셔야 합니다 :)

2023-10-26 07:53 UTC, yummyicecream approved these changes

2023-10-26 07:53 UTC, yummyicecream approved these changes

2023-10-26 08:02 UTC, soheon-lee approved these changes

2023-10-26 08:03 UTC, merged