Feature/userliked
wecode-bootcamp-korea/49-3rd-ifAreYouT-backend pull request #14
Opened 2023-10-19 11:12 UTC by namsuhan0322

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
- 마이페이지에서 자신이 좋아요를 누른 공연의 정보를 쉽게 볼수있다

  (예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  (예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

좋아요 조회 기능 추가

-좋아요 누른게 없을시 NOT_FOUND_LIKES 출력
-좋아요 누른 정보가 있을시 LIKED_EVENTS_FOUND 출력 

(예시) 로그인 기능 추가

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<img width="546" alt="스크린샷 2023-10-19 오후 8 07 51" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/142658057/0e51d8b0-9dfa-484e-9577-0b007914f105">

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

2023-10-19 14:14 UTC, soheon-lee requested changes

2023-10-19 14:14 UTC, soheon-lee commented on db/schema.sql
> +=======
마찬가지로 이거 꼭 고치셔야 합니다.

2023-10-19 14:14 UTC, soheon-lee commented on src/models/confirmationsDao.js
> +    WHERE event_reactions.user_id = ? AND event_reactions.reaction_type = 'exited';`,
```suggestion
    WHERE event_reactions.user_id = ? AND event_reactions.reaction_type = ?;`,
```
- reaction_type이 다른 종류가 될 수도 있기 때문에, 지금은 기대돼요 밖에 없을 지라도 백엔드에서는 확장성을 고려하여 변수로 받을 수 있도록 해두는 것이 좋습니다.
- parameter로 받아올 수 있도록 해주시고, default값을 exited로 두는 것을 추천드립니다.

2023-10-19 14:14 UTC, soheon-lee commented on src/models/confirmationsDao.js
> +const getUserLikeById = async (userId) => {
```suggestion
const getEventByUserReaction = async (userId, reactionType) => {
```

2023-10-19 14:14 UTC, soheon-lee commented on src/models/confirmationsDao.js
eventDao.js가 보다 명확한 이름일 것 같습니다.

2023-10-19 14:14 UTC, soheon-lee commented on src/controllers/index.js
> +}
여기에 Controller 추가 하셔야 하지 않나요?

2023-10-19 14:14 UTC, soheon-lee commented on src/routes/confirmationsRouter.js
> +const confirmationsController = require('../controllers/confirmationsController');
컨트롤러 모듈에 직접 접근 하기보다는 controllers 패키지에 접근하는 방식으로 모듈 불러와 주세요

2023-10-19 14:14 UTC, soheon-lee commented on src/routes/index.js
> +
```suggestion
router.use('/events', eventRouter);

```

2023-10-19 15:31 UTC, namsuhan0322 commented
수정했습니다! 그리고 컨플릭트가 gettickets 메인에 머지할때 남아있어서 gettickets도 수정했습니다!

2023-10-20 03:43 UTC, soheon-lee requested changes

2023-10-20 03:43 UTC, soheon-lee commented on src/controllers/eventController.js
> +  const reactionType = req.query.reaction_type || 'exited';
```suggestion
  const reactionType = req.query.reaction-type || 'exited';
```
query parameter를 포함한 url & uri에서는 언더바(`_`) 보단는 하이픈(`-`)으로 단어를 구분하는 것이 보다 일반적인 경우입니다.

2023-10-20 03:43 UTC, soheon-lee commented on src/controllers/eventController.js
> +const userByLikeController = async (req, res) => {
```suggestion
const getLikedEventsByUser = async (req, res) => {
```
수한님 함수명 지으실 때, 영어로 의미가 잘 통해야 합니다. 문법도 지키셔야 하고 의미도 전달이 가능해야해요.
userByLike -> 라는건 좋아요를 기준으로 유저를 가져온다는 의미로 오인될 가능성이 높습니다.
우리는 결국 사용자가 좋아요한 이벤트를 가지고 오는 것이기 때문에 수정하시는 것이 좋을 것 같습니다. :)

2023-10-20 03:43 UTC, soheon-lee commented on src/controllers/eventController.js
> +
```suggestion

    if (!likesInfo) {
      throwError(400, 'LIKED_EVENTS_NOT_FOUND');
    }

```

2023-10-20 03:43 UTC, soheon-lee commented on src/controllers/eventController.js
> +};
```suggestion
  } catch (error) {
    console.log(error);
    return res.status(500).json(error);
  }
};
```
- 이유를 알 수 없는 에러는 500에러입니다.

2023-10-20 03:43 UTC, soheon-lee commented on src/models/eventDao.js
> +const getUserLikeById = async (userId, reactionType) => {
```suggestion
const getLikedEventsByUserId = async (userId, reactionType) => {
```

2023-10-20 03:43 UTC, soheon-lee commented on src/models/eventDao.js
> +    SELECT events.*
events의 모든 컬럼을 사용하실 게 아니라면, 사용하실 컬럼명만 정확히 SELECT 해주시는 것이 좋습니다.

2023-10-20 03:43 UTC, soheon-lee commented on src/services/eventService.js
> +  return likesInfo;
likesInfo가 없을 때 발생하는 Error처리를 service layer에서도 하시고 있고, controller layer에서도 하시고 있는데, 둘 중 하나만 동작합니다. 불필요한 부분은 제거해 주시고, 에러를 핸들링하는 관리포인트 기점은 한군데에서 관리하셔야 합니다 :)

2023-10-20 03:43 UTC, soheon-lee commented on tests/userLike.test.js
> +describe('user get likes', () => {
```suggestion
describe('get events with reaction by user', () => {
```

2023-10-20 03:43 UTC, soheon-lee commented on tests/userLike.test.js
> +  });
- 테스트 함수 내에는 try-catch가 있을 필요가 없습니다.에러 핸들링은 API 내부에서 처리되어야 해요

2023-10-20 03:43 UTC, soheon-lee commented on tests/userLike.test.js
> +      expect(res.body.message).toEqual('NOT_FOUND_LIKES');
마찬가지로 res.body에 있는 데이터까지 모두 테스트 하셔야 합니다 :)

2023-10-26 08:03 UTC, soheon-lee approved these changes

2023-10-26 09:38 UTC, merged