Feature/order
wecode-bootcamp-korea/49-3rd-ifAreYouT-backend pull request #18
Opened 2023-10-21 02:36 UTC by 03290419

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 고객은 공연 정보를 기반으로 예매 가능한 좌석을 확인할 수 있습니다. 

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

- 좌석 데이터 생성 및  좌석 데이터 가져오기 api 개발 

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<img width="888" alt="스크린샷 2023-10-21 오전 11 32 02" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/58713222/9ec8dfca-4758-4505-8ed3-c9ca5fcb3a0c">
<img width="826" alt="스크린샷 2023-10-21 오전 11 33 19" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/58713222/4b859843-f6bb-4bff-9c31-f64d1af8d90e">

## 4. 이 브랜치에서 개발하면서 느꼈던 개발 성장포인트를 적어주세요.

- 테스트코드 작성
- 재사용 가능한 코드 작성

2023-10-23 06:01 UTC, soheon-lee requested changes
1. 해당 브랜치에서 dbmate up 했을 때 migration이 안되는데 혹시 괜찮나요?

<img width="613" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-ifAreYouT-backend/assets/42701133/33a9f2c6-5d79-4358-934f-bc92ea3b50a4">

2. 아래 코멘트 확인 부탁드립니다 :)

2023-10-23 06:01 UTC, soheon-lee commented on src/controllers/orderController.test.js
> +        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6MX0sImlhdCI6MTY5NzcxOTY0MiwiZXhwIjoxNzAwMzExNjQyfQ.zuVcbarIWTuPPBm7DvoaYRsKGFV8YJPK68fa2gztFeU',
이 토큰은 만료 안되나요? 테스트코드에서 계속 쓸 수 있는지 궁금합니다.

2023-10-23 06:01 UTC, soheon-lee commented on src/models/orderDao.js
> +    getDetailsQuery,
SELECT 문은 데이터베이스 상에서 데이터를 수정/삭제/생성 하지 않기 때문에 굳이 transaction을 걸 필요는 없습니다 :) 중간에 오류 상황이 발생해도 rollback해서 돌아가야할 상태가 없기 때문입니다-!

2023-10-23 06:01 UTC, soheon-lee commented on src/controllers/orderController.js
> +    if (isEmpty(eventExist)) throwError(400, 'no event data');
여기 에러 처리는 service layer로 이동하시는 것이 보다 역할상 적절할 것 같습니다.
이벤트 존재하지않는 것이 에러라는 것은 request나 response와 관련되어 있다기 보다는 우리 비즈니스상에서의 예외적인 상황이기 때문입니다.

2023-10-23 06:01 UTC, soheon-lee commented on src/controllers/orderController.js
> +    const seatsData = await getSeatsDataService(eventId);
```suggestion
    const seatsData = await getSeatsDataByEvent(eventId);
```
1. 레이어의 모든 함수이름 뒤에 `service`, `controller`, `dao` 단어가 붙어있는데, 팀내 다른 분들 함수에는 안붙어 있어서, 정해진 컨벤션이 없다면 맞추시는게 좋을 것 같습니다-!
2. 이벤트로 걸러서 데이터를 추출하는 과정이므로, 어떤 entity의 id를 넘기는 지 함수명에서 명시하시는 것이 좋습니다.

2023-10-23 06:02 UTC, soheon-lee commented on src/controllers/orderController.test.js
> +});
content 타입으로만으로는 해당 API가 정상동작한다고, 그 안정성을 신뢰할 수가 없습니다 :)
데이터 자체가 의도대로 잘 출력되는지 확인하기 위해, res.body를 전부 점검해 주세요!

2023-10-23 06:37 UTC, 03290419 commented on src/controllers/orderController.test.js
> +        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6MX0sImlhdCI6MTY5NzcxOTY0MiwiZXhwIjoxNzAwMzExNjQyfQ.zuVcbarIWTuPPBm7DvoaYRsKGFV8YJPK68fa2gztFeU',
30일 뒤에 만료되도록 되어있습니다~!

2023-10-23 06:38 UTC, 03290419 commented on src/controllers/orderController.test.js
> +        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6MX0sImlhdCI6MTY5NzcxOTY0MiwiZXhwIjoxNzAwMzExNjQyfQ.zuVcbarIWTuPPBm7DvoaYRsKGFV8YJPK68fa2gztFeU',
20231019051552_seats.sql 파일에서 오류가 발생할 듯 하여 해당 파일 삭제 후 migrate 해주시면 오류 없이 실행될 것으로 생각됩니다! (해당 변경은 db관련이라 improve/dbschema브랜치에 적용해두었습니다)

2023-10-25 08:02 UTC, 03290419 commented on src/controllers/orderController.test.js
> +});
response.body 검증 로직 추가했습니다~

2023-10-25 08:04 UTC, 03290419 commented on src/controllers/orderController.js
> +    const seatsData = await getSeatsDataService(eventId);
원래는 컨벤션이 맞으나 잘 지켜지지 않은 것 같습니다 🥲 이름을 바꿔야 한다면 단순히 dao를 리턴하는 service의 경우 이름 짓기가 모호한 감이 있어서 접미사로 구분해야 할 것 같습니다

2023-10-25 08:04 UTC, 03290419 commented on src/controllers/orderController.js
> +    if (isEmpty(eventExist)) throwError(400, 'no event data');
에러 처리 서비스로 이관했습니다~

2023-10-25 08:11 UTC, soheon-lee approved these changes
죄송해요 ...ㅎ

2023-10-25 08:16 UTC, merged