feature: 공통 초기 세팅 추가사항
wecode-bootcamp-korea/49-3rd-ifAreYouT-backend pull request #9
Opened 2023-10-13 11:40 UTC by 03290419

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 본 레포의 동료 개발자들이 개선된 환경에서 프로젝트 개발을 진행할 수 있습니다.

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

- 프로덕션/테스트/개발 환경의 분리를 개선합니다.
- 테스트를 위해 jest 및 supertest 의존성을 추가합니다.
- db 스키마를 개선합니다.

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 프로덕션/테스트/개발 환경 분리 고찰 
- .env 사용법

2023-10-13 11:45 UTC, soheon-lee requested changes

2023-10-13 11:45 UTC, soheon-lee commented on package.json
> +    "start": "DOTENV_CONFIG_PATH=.env.prod node server.js"
```suggestion
    "dev": "DOTENV_CONFIG_PATH=.env.dev nodemon server.js",
    "start": "DOTENV_CONFIG_PATH=.env.prod nodemon server.js"
```

둘 다 nodemon으로 통합하는 방향을 추천드립니다

2023-10-13 11:45 UTC, soheon-lee commented on src/models/dataSource.js
> +  type: 'mysql',
DB type도 환경변수로 독립시켜주세요! :)

2023-10-14 07:33 UTC, 03290419 commented on src/models/dataSource.js
> +  type: 'mysql',
type도 독립 완료했습니다!

2023-10-16 01:35 UTC, soheon-lee approved these changes

2023-10-16 01:37 UTC, merged